spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sepdetect2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: antares.powerworxx.de
    port: 465
    username: mailer-daemon@sepdetect.com
    properties:
      mail:
        debug: false
        smtp:
          starttls.enable: true
          ssl.trust: antares.powerworxx.de
          auth: false
    protocol: smtps
    password: 5xFrt!s(r54-FGwRt

server:
  port: 8081

sepdetect:
  secret: SecretKeyToGenJWTs
  securitySettings:
    secret: "SecretKeyToGenJWTs"
    expiration_time: 864000000
    token_prefix: "Bearer "
    header_string: "Authorization"
    sign_in: "/login"
  default:
    debugdata: false
    adminMails:
      - glatzan@gmail.com